### PR TITLE
Match event.originalTarget also in handleClick (fixes #14)

### LINKED ISSUE #14: Doesn't work in AUTOMATIC111/stable-diffusion-webui
[AUTOMATIC111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) is web UI for Stable Diffusion.

When I clicked "Upload" I get "file choose" system dialog.
I debug 'click' event propagation and `handleClick` has invoked and I see `event.target` doesn't contain `input[type=file]` but `event.originalTarget` does. It's because "AUTOMATIC111/stable-diffusion-webui" uses complex web framework (svelte.js).

I think `handleClick` may check both `event.target` and `event.originalTarget` to fix this issue.

### PR DESCRIPTION
**Pull request by antage**
See the issue #14.

I test it on imgur.com and stable-diffusion-webui and it works fine.

### CODE REVIEW

**Comment by vord1080** [comment]
I have some concerns with this approach. Mainly: If a fully synthetic (script-driven) click event only matches `originalTarget`, we won't be able to preventDefault() the OS native file picker, I think, and the extension will be in this weird state where it technically succeeded but the OS native file picker still opened.

**Comment by antage** [comment]
I didn't see such behaviour but I agree this solution isn't very elegant.
Is `stopPropogation()` better if `originalTarget` matched?

**Comment by vord1080** [comment]
stopPropogation() won't help us here. We have to use preventDefault() and it HAS to be on a 'trusted' event, otherwise we can't override behavior and stop the native file picker from opening. Some web frameworks handle events weirdly, so ALL of their events end up technically being 'untrusted'.

**Comment by vord1080** [comment]
So here's my concern:
Event.originalTarget is Firefox-specific, I don't care personally, I only develop this extension for Firefox because it is my favorite web browser. The problem is that Mozilla likes to remove their non-standard features, so its possible that they will remove this property from Firefox in the future, so I've tried to avoid using it.

Another issue is that I don't fully understand how it interacts with trusted events/input behavior. For example, try this website with your proposed changes:
https://www.webcomponents.org/element/@fluidnext-polymer/paper-input-file/demo/demo/index.html (you have to click the magnifying glass).
With your proposed change, you can see the image popup open for a split second, but then the native file picker opens, it looks broken.

With the current version of the extension, this case is just completely ignored, which is more consistent and avoids website breaking. It is very confusing, I'm not sure what to do. If we could detect these cases, then everything will work, but I can't figure out how to detect when we're actually able to override the native picker.

**Comment by antage** [comment]
I agree it is arguable solution so I close PR.

**Comment by vord1080** [comment]
I did more research so i think this is a good solution now.

**Comment by antage** [comment]
I'm curious, what changed your mind?

**Comment by vord1080** [comment]
i figured out how https://www.webcomponents.org/element/@fluidnext-polymer/paper-input-file/demo/demo/index.html bypassed the extension (dispatching an uncancellable click event with dispatchEvent function). i added new code to handle that case and a few others.

**Pull request merged**
